org: tomploetz1
app: hello-serverless
service: sls

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: dev

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 3
    vpc:
      securityGroupIds:
        - sg-57063e3d
      subnetIds:
        - subnet-0e817d42
        - subnet-6f603f07
  
  add:
    handler: add.add
    memorySize: 256
    timeout: 10
    events:
      - http:
          path: math/add
          method: post
          cors: true

plugins:
  - serverless-offline